openapi: 3.0.0
info:
  title: AI
  version: '1.0'
servers:
  - url: https://api.alcmeon.com
    description: Alcmeon production API server
x-readme:
  explorer-enabled: false

components:

  securitySchemes:
    basic_auth:
      type: http
      scheme: basic



paths:
  /ai/answer:
    post:
      summary: Send AI generated answer
      description: >
        Endpoint to call when you want to send an AI generated answer: once your AI server is triggered, it can use the 
        jwt previously received to forward the generated answer to the end user in social network.

      parameters:
        - in: header
          name: X-JWT
          schema:
            type: string
            description: the JWT received (e.g. the 'jwt' field of the payload sent by the AI-connector box).
          required: true
      requestBody:
        content:
          application/json:
            schema:
              required: [message]
              properties:
                message:
                  type: object
                  nullable: true
                  description: An object containing information about the generated answer
                  properties:
                    id:
                      type: string
                      description: >
                        The identifier for a generated response
                    content:
                      type: string
                      description: >
                        The content of the generated response
                error:
                  type: object
                  nullable: true
                  description: An object containing information about the error returned when the AI did not manage
                               to generate a satisfying answer
                  properties:
                    code:
                      type: string
                      nullable: true
                      description: >
                        A string identifying the type of error of the AI
                    details:
                      type: string
                      nullable: true
                      description: >
                        Some more information about the error
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '400':
          description: If the token used to call the endpoint is not valid (or expired) or if the received json
                        does not match with the expected format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
