openapi: 3.0.0
info:
  title: AI Webhooks
  version: '1.0'
x-readme:
  explorer-enabled: false

components:
  schemas:
    HTTPError:
      properties:
        detail:
          type: object
        message:
          type: string
      type: object
    ValidationError:
      properties:
        detail:
          type: object
          properties:
            <location>:
              type: object
              properties:
                <field_name>:
                  type: array
                  items:
                    type: string
        message:
          type: string
      type: object
    SuggestStatsInput:
      type: object
      properties:
        question:
          type: string
        context:
          type: array
          items:
            type: string
        suggestion:
          type: string
        answer:
          type: string
        status:
          enum:
          - rejected
          - accepted
          - edited
      required:
      - context
      - question
    ResponseOk:
      type: string
      enum: ['ok']
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /suggest-answer:
    post:
      tags:
      - Suggest Answer
      summary: Ask for a suggestion answer for a support agent
      description: >
        Webhook to implement to send an AI generated suggestion to a support agent.
        This webhook can be protected by checking the bearer, a jwt that can be decoded with the public key provided when this webhook is declared.
        The token has a validity limit of 60 seconds.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - version
              - question
              - context
              - webhook_token
              properties:
                version:
                  type: string
                  enum:
                    - '1.0'
                question:
                  type: string
                context:
                  type: array
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                        enum:
                          - bot
                          - agent
                          - user
                          - system
                      content:
                        type: string
                webhook_token:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - id
                - status
                properties:
                  id:
                    type: integer
                  status:
                    enum:
                    - pending
                    - started
                    - finished
                    - failed
          description: Successful response
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Authentication error
      security:
      - BearerAuth: []

  /suggest-stats:
    post:
      tags:
      - Suggest Statistics
      summary: Provide statistics about a suggested answer
      description: 'Provide statistics about a suggested answer'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOk'
          description: Successful response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Validation error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Authentication error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuggestStatsInput'
      security:
      - BearerAuth: []