openapi: 3.0.0
info:
  title: AI Webhooks
  version: '1.0'
x-readme:
  explorer-enabled: false

components:
  schemas:
    HTTPError:
      properties:
        detail:
          type: object
        message:
          type: string
      type: object
    ValidationError:
      properties:
        detail:
          type: object
          properties:
            <location>:
              type: object
              properties:
                <field_name>:
                  type: array
                  items:
                    type: string
        message:
          type: string
      type: object
    SuggestAnswerOutput:
      type: object
      properties:
        id:
          type: integer
        status:
          enum:
          - pending
          - started
          - finished
          - failed
        answer:
          type: string
        created_at:
          type: string
          format: date-time
          nullable: true
        finished_at:
          type: string
          format: date-time
          nullable: true
      required:
      - created_at
      - id
      - status
    SuggestAnswerInput:
      type: object
      properties:
        question:
          type: string
        context:
          type: array
          items:
            type: string
      required:
      - context
      - question
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /suggest-answer:
    post:
      summary: Create a new suggest answer
      description: 'creates a new suggested answer '
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuggestAnswerOutput'
          description: Successful response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Validation error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Authentication error
      tags:
      - Suggest Answer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuggestAnswerInput'
      security:
      - BearerAuth: []