openapi: 3.0.0
servers:
  - url: https://api.alcmeon.com/
    description: Production api server
info:
  title: Custom Fields
  version: '1.0'

security:
  - basic_auth: []

components:
  securitySchemes:
    basic_auth:
      description: >
        This is the default authentication schema for api.alcmeon.com.
        The username is your `company_id` (the id of your environment within Alcméon).
        The password is available from the _Applications_ configuration page within Alcméon.
      type: http
      scheme: basic

  schemas:
    PrimitiveFieldValues:
      oneOf:
        - type: integer
          description: When the field is of type integer
        - type: number
          description: When the field is of type float
        - type: string
          description: When the field is of type string
        - type: string
          format: uri
          description: When the field is of type url
        - type: string
          format: email
          description: When the field is of type email
        - type: string
          format: date-time
          description: When the field is of type datetime
        - type: string
          format: date
          description: When the field is of type date
        - type: boolean
          description: When the field is of type boolean
        - type: string
          format: uuid
          description: When the field is of type enum
        - $ref: '#/components/schemas/MultiPickListFieldValue'
        - $ref: '#/components/schemas/PhoneFieldValue'

    PhoneFieldValue:
      description: When the field is of type Phone
      type: object
      properties:
        country_prefix:
          type: string
        number:
          type: string

    MultiPickListFieldValue:
      description: When the field is of type multi-picklist
      type: array
      items:
        type: string
        format: uuid

    FieldValues:
      description: A list of field/value pairs
      type: array
      items:
        type: object
        description: A value for a specific field
        properties:
          field_id:
            type: integer
          field_value:
            $ref: '#/components/schemas/PrimitiveFieldValues'

paths:
  /custom-field/users/{custom_field_user_id}:
    parameters:
      - in: path
        name: custom_field_user_id
        description: A custom_field_user_id which uniquely identifies a user.
        required: true
        schema:
          type: integer
    put:
      tags:
        - User
      summary: Set user fields
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FieldValues'
      responses:
        '200':
          description: Returned upon succes
    get:
      tags:
        - User
      summary: Return user fields
      responses:
        '200':
          description: Returned upon succes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldValues'

  /custom-field/conversations/{conversation_id}:
    parameters:
      - in: path
        name: conversation_id
        description: A conversation_id which uniquely identifies a conversation
        required: true
        schema:
          type: integer
    put:
      tags:
        - Conversation
      summary: Set conversation fields
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FieldValues'
      responses:
        '200':
          description: Returned upon succes
    get:
      tags:
        - Conversation
      summary: Return conversation fields
      responses:
        '200':
          description: Returned upon succes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldValues'
