openapi: 3.0.0
info:
  title: Subbot for Whatsapp
  version: '1.0'

components:
  schemas:
    Whatsapp_Media:
      description: >
        a Media object. The data the url points to is cached. The cache key is the url itself.
      type: object
      properties:
        link:
          type: string
          format: uri
        caption:
          type: string
          maxLength: 1024
      required: [link]

    Whatsapp_Document_Media:
      allOf:
        - $ref: '#/components/schemas/Whatsapp_Media'
        - type: object
          properties:
            filename:
              type: string
              description: The extension of the filename will specify what format the document is displayed as in WhatsApp.

    Whatsapp_Image_Message:
      title: Image Message
      type: object
      properties:
        type:
          type: string
          enum: [image]
        image:
          $ref: '#/components/schemas/Whatsapp_Media'
      required: [type, image]

    Whatsapp_Audio_Message:
      title: Audio Message
      type: object
      properties:
        type:
          type: string
          enum: [audio]
        audio:
          $ref: '#/components/schemas/Whatsapp_Media'
      required: [type, audio]

    Whatsapp_Video_Message:
      title: Video Message
      type: object
      properties:
        type:
          type: string
          enum: [video]
        video:
          $ref: '#/components/schemas/Whatsapp_Media'
      required: [type, video]

    Whatsapp_Document_Message:
      title: Document Message
      type: object
      properties:
        type:
          type: string
          enum: [document]
        document:
          $ref: '#/components/schemas/Whatsapp_Document_Media'
      required: [type, document]

    Whatsapp_Interactive_Base:
      type: object
      properties:
        type:
          type: string
          enum: [interactive]
        interactive:
          type: object
          properties:
            footer:
              type: object
              properties:
                text:
                  type: string
                  maxLength: 60
                  description: Required if footer is present. The footer content. Emojis, markdown, and links are supported.
      required: [type, interactive]

    Whatsapp_Interactive_Document_Header:
      allOf:
        - $ref: '#/components/schemas/Whatsapp_Document_Message'
        
    Whatsapp_Interactive_Image_Header:
      allOf:
        - $ref: '#/components/schemas/Whatsapp_Image_Message'
        
    Whatsapp_Interactive_Video_Header:
      allOf:
        - $ref: '#/components/schemas/Whatsapp_Video_Message'
        
    Whatsapp_Interactive_Text_Header:
      type: object
      properties:
        type:
          type: string
          enum: [text]
        text:
          type: string
          maxLength: 60
          description: Text for the header. Formatting allows emojis, but not markdown.

    Whatsapp_Interactive_Body:
      type: object
      properties:
        text:
          description: Emojis, markdown, and links are supported
          type: string
          maxLength: 1024
      required: [text]

    Whatsapp_List_Message:
      title: List Message
      allOf:
        - $ref: '#/components/schemas/Whatsapp_Interactive_Base'
        - type: object
          properties:
            interactive:
              type: object
              properties:
                type:
                  type: string
                  enum: [list]
                header:
                  $ref: '#/components/schemas/Whatsapp_Interactive_Text_Header'
                body:
                  $ref: '#/components/schemas/Whatsapp_Interactive_Body'
                action:
                  type: object
                  properties:
                    button:
                      type: string
                      description: Emojis are supported, markdown is not.
                      maxLength: 20
                    sections:
                      type: array
                      minLength: 1
                      maxLength: 10
                      items:
                        type: object
                        properties:
                          title:
                            description: Required if the message has more than one section.
                            type: string
                            maxLength: 24
                          rows:
                            description: Limited to 10 rows across all sections.
                            type: array
                            items:
                              type: object
                              properties:
                                ID:
                                  type: string
                                  maxLength: 200
                                title:
                                  type: string
                                  maxLength: 24
                              required: [ID, title]
                        required: [rows]
                  required: [button]
              required: [type, body, action]

    Whatsapp_Product_Action:
      type: object
      properties:
        catalog_id:
          type: string
          description: Unique identifier of the Facebook catalog linked to your WhatsApp Business Account. This ID can be retrieved via Commerce Manager.
        product_retailer_id:
          type: string
          maxLength: 100
      required: [catalog_id, product_retailer_id]

    Whatsapp_Product_Message:
      title: Product Message
      allOf:
        - $ref: '#/components/schemas/Whatsapp_Interactive_Base'
        - type: object
          properties:
            interactive:
              type: object
              properties:
                type:
                  type: string
                  enum: [product]
                body:
                  $ref: '#/components/schemas/Whatsapp_Interactive_Body'
                action:
                  $ref: '#/components/schemas/Whatsapp_Product_Action'
              required: [type, action]

    Whatsapp_Product_List_Message:
      title: Product List Message
      allOf:
        - $ref: '#/components/schemas/Whatsapp_Interactive_Base'
        - type: object
          properties:
            interactive:
              type: object
              properties:
                type:
                  type: string
                  enum: [product_list]
                header:
                  $ref: '#/components/schemas/Whatsapp_Interactive_Text_Header'
                body:
                  $ref: '#/components/schemas/Whatsapp_Interactive_Body'
                action:
                  allOf:
                    - $ref: '#/components/schemas/Whatsapp_Product_Action'
                    - type: object
                      properties:
                        sections:
                          type: object
                          properties:
                            title:
                              type: string
                              maxLength: 24
                            product_items:
                              type: array
                              items:
                                type: object
                                properties:
                                  product_retailer_id:
                                    type: string
                                required: [product_retailer_id]
                          required: [title, product_items]
                      required: [sections]
              required: [type, header, body, action]

    Whatsapp_Button_Message:
      title: Button Message
      allOf:
        - $ref: '#/components/schemas/Whatsapp_Interactive_Base'
        - type: object
          properties:
            interactive:
              type: object
              properties:
                type:
                  type: string
                  enum: [button]
                header:
                  oneOf:
                    - $ref: '#/components/schemas/Whatsapp_Interactive_Document_Header'
                    - $ref: '#/components/schemas/Whatsapp_Interactive_Image_Header'
                    - $ref: '#/components/schemas/Whatsapp_Interactive_Video_Header'
                    - $ref: '#/components/schemas/Whatsapp_Interactive_Text_Header'
                body:
                  $ref: '#/components/schemas/Whatsapp_Interactive_Body'
                action:
                  type: object
                  properties:
                    buttons:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                            enum: [reply]
                          title:
                            type: string
                            description:  Button title. It cannot be an empty string and must be unique within the message. Emojis are supported, markdown is not. 
                            maxLength: 20
                          id:
                            type: string
                            maxLength: 256
                            description: Unique identifier for your button. This ID is returned in the webhook when the button is clicked by the user. You cannot have leading or trailing spaces.
                        required: [type, id, title]
                  required: [buttons]
              required: [type, body, action]

    Whatsapp_Text_Message:
      title: Text Message
      type: object
      properties:
        type:
          type: string
          enum: [text]
        text:
          type: object
          properties:
            body:
              type: string
              description: the text of the message. See [Formatting](https://developers.facebook.com/docs/whatsapp/on-premises/reference/messages#formatting)
            preview_url:
              type: boolean
              default: false
              description: >
                If true, Whatsapp will attempt to generate a preview within the Whatsapp application.
                Note: this field is located in the text.body object on purpose, to mirror the 
                Whatsapp cloud API. We automatically convert that field to the proper field if
                using the on-premise API.
                [Limitations](https://developers.facebook.com/docs/whatsapp/api/messages/text#urls)
          required: [body]
      required: [type, text]

    Whatsapp_Message:
      title: Whatsapp Message
      description: >
        On Whatsapp, a subset of the [message](https://developers.facebook.com/docs/whatsapp/api/messages#parameters) object.
      oneOf:
        - $ref: '#/components/schemas/Whatsapp_Text_Message'
        - $ref: '#/components/schemas/Whatsapp_Image_Message'
        - $ref: '#/components/schemas/Whatsapp_Audio_Message'
        - $ref: '#/components/schemas/Whatsapp_Document_Message'
        - $ref: '#/components/schemas/Whatsapp_Video_Message'
        - $ref: '#/components/schemas/Whatsapp_List_Message'
        - $ref: '#/components/schemas/Whatsapp_Button_Message'
        - $ref: '#/components/schemas/Whatsapp_Product_Message'
        - $ref: '#/components/schemas/Whatsapp_Product_List_Message'

    Whatsapp_Text_Event:
      title: Text Event
      type: object
      required: [type, text]
      properties:
        type:
          type: string
          enum: [text]
        text:
          type: object
          required: [body]
          properties:
            body:
              type: string

    Whatsapp_Media_Event:
      type: object
      required: [link, mime_type, caption]
      properties:
        link:
          type: string
          format: uri
        mime_type:
          type: string
        caption:
          type: string

    Whatsapp_Image_Event:
      title: Image Event
      type: object
      required: [type, image]
      properties:
        type:
          type: string
          enum: [image]
        image:
         $ref: '#/components/schemas/Whatsapp_Media_Event' 

    Whatsapp_Audio_Event:
      title: Audio Event
      type: object
      required: [type, audio]
      properties:
        type:
          type: string
          enum: [audio]
        audio:
         $ref: '#/components/schemas/Whatsapp_Media_Event' 

    Whatsapp_Document_Event:
      title: Document Event
      type: object
      required: [type, document]
      properties:
        type:
          type: string
          enum: [document]
        document:
         $ref: '#/components/schemas/Whatsapp_Media_Event'

    Whatsapp_Interactive_Event:
      type: object
      required: [type, interactive] 
      properties:
        type:
          type: string
          enum: [interactive]
        interactive:
          type: object
          required: [type]
          properties:
            type:
              type: string

    Whatsapp_Button_Event:
      title: Button Event
      allOf:
        - $ref: '#/components/schemas/Whatsapp_Interactive_Event'
        - type: object
          required: [interactive] 
          properties:
            interactive:
              type: object
              required: [type, button_reply]
              properties:
                type:
                  type: string
                  enum: [button_reply]
                button_reply:
                  type: object
                  required: [id, title]
                  properties:
                    id:
                      type: string
                    title:
                      type: string

    Whatsapp_List_Event:
      title: List Event
      allOf:
        - $ref: '#/components/schemas/Whatsapp_Interactive_Event'
        - type: object
          required: [interactive] 
          properties:
            interactive:
              type: object
              required: [type, list_reply]
              properties:
                type:
                  type: string
                  enum: [list_reply]
                list_reply:
                  type: object
                  required: [id, title, description]
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string

    Whatsapp_Order_Event:
      title: Order Event
      type: object
      required: [type, order]
      properties:
        type:
          type: string
          enum: [order]
        order:
          type: object
          required: [catalog_id, product_items, text]
          properties:
            text:
              type: string
            catalog_id:
              type: string
            product_items:
              type: array
              items:
                type: object
                required: [product_retailer_id, quantity, item_price, currency]
                properties:
                  product_retailer_id:
                    type: string
                  quantity:
                    type: integer
                  item_price:
                    type: number
                  currency:
                    type: string
                    enum: [EUR]

    Whatsapp_Event:
      title: Whatsapp Event
      description: >
        On Whatsapp, a subset of the [message notifications](https://developers.facebook.com/docs/whatsapp/on-premises/webhooks/components#messages_object)
      oneOf:
        - $ref: '#/components/schemas/Whatsapp_Text_Event'
        - $ref: '#/components/schemas/Whatsapp_Image_Event'
        - $ref: '#/components/schemas/Whatsapp_Audio_Event'
        - $ref: '#/components/schemas/Whatsapp_Document_Event'
        - $ref: '#/components/schemas/Whatsapp_Button_Event'
        - $ref: '#/components/schemas/Whatsapp_List_Event'
        - $ref: '#/components/schemas/Whatsapp_Order_Event'


