openapi: 3.0.0
info:
  title: Subbot for Instagram
  version: '1.0'

components:
  schemas:
    Instagram_Text_Event:
      title: Text Event
      description: >
        A message of type [Text](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messages#messaging)
      type: object
      required: [message]
      properties:
        message:
          type: object
          required: [text]
          properties:
            text:
              type: string
              description: The text message to send

    Instagram_Postback_Event:
      title: Postback Event
      description: >
        A trimmed version of the [postback webhook](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_postbacks).
      type: object
      required: [postback]
      properties:
        postback:
          type: object
          required: [payload]
          properties:
            payload:
              description: payload parameter that was defined with the button.
              type: string


    Instagram_Event:
      title: Instagram Event
      description: A message sent by a user to a brand
      oneOf:
        - $ref: '#/components/schemas/Instagram_Text_Event'
        - $ref: '#/components/schemas/Instagram_Postback_Event'

    Instagram_Text_Message:
      title: Text Message
      description: A text message
      type: object
      required: [text]
      properties:
        text:
          description: the text of the message to send.
          type: string

    Instagram_WebUrl_Button:
      type: object
      required: [type, url, title]
      properties:
        type:
          type: string
          enum: [web_url]
        url:
          type: string
          format: uri
        title:
          type: string

    Instagram_Postback_Button:
      type: object
      required: [type, title, payload]
      properties:
        type:
          type: string
          enum: [postback]
        title:
          type: string
        payload:
          type: string

    Instagram_Button:
      oneOf:
        - $ref: '#/components/schemas/Instagram_WebUrl_Button'
        - $ref: '#/components/schemas/Instagram_Postback_Button'

    Instagram_Carousel_Message:
      title: Carousel Message
      type: object
      properties:
        attachment:
          type: object
          properties:
            type:
              type: string
              enum: [template]
            payload:
              type: object
              required: [template_type, elements]
              properties:
                template_type:
                  type: string
                  enum: [generic]
                elements:
                  type: array
                  items:
                    type: object
                    required: [title]
                    properties:
                      title:
                        type: string
                        description: the title to display
                        maxLength: 80
                      subtitle:
                        type: string
                        description: the subtitle to display
                        maxLength: 80
                      image_url:
                        type: string
                        format: uri
                      buttons:
                        type: array
                        items:
                          $ref: '#/components/schemas/Instagram_Button'


    Instagram_Message:
      title: Instagram Message
      description: A message sent by a brand to a user.
      oneOf:
        - $ref: '#/components/schemas/Instagram_Text_Message'
        - $ref: '#/components/schemas/Instagram_Carousel_Message'


