openapi: 3.0.0
info:
  title: Subbot for Messenger
  version: '1.0'

components:
  schemas:
    MessengerUrlButton:
      description: >
        A [UrlButton](https://developers.facebook.com/docs/messenger-platform/reference/buttons/url)
      type: object
      properties:
        type:
          type: string
          enum: [web_url]
        title:
          type: string
          maxLength: 20
        url:
          type: string
          format: uri
        webview_height_ratio:
          type: string
          enum: [compact, tall, full]
        messenger_extensions:
          type: boolean
        fallback_url:
          type: string
          format: uri
        webview_share_button:
          type: string
          enum: [hide]
          nullable: true

    MessengerPostbackButton:
      description: >
        A [Postback button](https://developers.facebook.com/docs/messenger-platform/reference/buttons/postback)
      type: object
      properties:
        type:
          type: string
          enum: [postback]
        title:
          type: string
          maxLength: 20
        payload:
          description: The Messenger Length limit for this field is 1000 but we restrict it to 900.
          type: string
          maxLength: 900

    MessengerCallButton:
      description: >
        A [Call button](https://developers.facebook.com/docs/messenger-platform/reference/buttons/call)
      type: object
      properties:
        type:
          type: string
          enum: [phone_number]
        title:
          type: string
          maxLength: 20
        payload:
          type: string

    MessengerLoginButton:
      description: >
        A [Login button](https://developers.facebook.com/docs/messenger-platform/reference/buttons/login)
      type: object
      properties:
        type:
          type: string
          enum: [account_link]
        url:
          type: string
          format: uri

    MessengerLogoutButton:
      description: >
        A [Logout button](https://developers.facebook.com/docs/messenger-platform/reference/buttons/logout)
      type: object
      properties:
        type:
          type: string
          enum: [account_unlink]

    MessengerGamePlayButton:
      description: >
        A [Game play button](https://developers.facebook.com/docs/messenger-platform/reference/buttons/game-play)
      type: object
      properties:
        type:
          type: string
          enum: [game_play]
        title:
          type: string
        payload:
          type: string
        game_metadata:
          type: object
          properties:
            player_id:
              type: string
            context_id:
              type: string
      

    MessengerButton:
      description: >
        A [Button](https://developers.facebook.com/docs/messenger-platform/send-messages/buttons)
      oneOf:
        - $ref: '#/components/schemas/MessengerUrlButton'
        - $ref: '#/components/schemas/MessengerPostbackButton'
        - $ref: '#/components/schemas/MessengerCallButton'
        - $ref: '#/components/schemas/MessengerLoginButton'
        - $ref: '#/components/schemas/MessengerLogoutButton'
        - $ref: '#/components/schemas/MessengerGamePlayButton'
      
    MessengerButtonPayload:
      description: >
        A [payload field](https://developers.facebook.com/docs/messenger-platform/reference/templates/button#payload)
        of a Button template.
      type: object
      properties:
        template_type:
          type: string
          enum: [button]
        text:
          type: string
          maxLength: 640
        buttons:
          type: array
          items:
            $ref: '#/components/schemas/MessengerButton'

    MessengerMessage:
      title: Messenger Message
      description: >
        On Messenger, a trimmed down version of the 
        [message](https://developers.facebook.com/docs/messenger-platform/reference/send-api#message) object.
      type: object
      properties:
        text:
          description: Message text.
          type: string
          maxLength: 2000
        attachment:
          type: object
          properties:
            type:
              type: string
              enum: [template]
            payload:
              oneOf:
                - $ref: '#/components/schemas/MessengerButtonPayload'
        quick_replies:
          type: array
          items:
            description: >
              A [quick_reply](https://developers.facebook.com/docs/messenger-platform/reference/buttons/quick-replies#quick_reply) object
            type: object
            properties:
              content_type:
                type: string
                enum: [text, user_phone_number, user_email]
              title:
                type: string
                maxLength: 20
              payload:
                description: The Messenger Length limit for this field is 1000 but we restrict it to 900.
                type: string
                maxLength: 900
              image_url:
                type: string
                format: url
            
    MessengerEvent:
      title: Messenger Event
      description: >
        On Messenger, a trimmed down version of the
        [message](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messages),
        [messaging_postback](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_postbacks), and,
        [messaging_account_linking](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_account_linking)
        webhook events. Only the fields described below will be sent to the application.
      type: object
      properties:
        message:
          description: >
            A trimmed down version of the [messaging](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messages#messaging) field of the `message` webhook event.
          type: object
          properties:
            text:
              type: string
              description: Text of message
            quick_reply:
              description: Optional custom data provided by the sending app
              type: object
              properties:
                payload:
                  type: string
                  description: Custom data provided by the app
        postback:
          description: >
            A trimmed version of the [postback](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_postbacks#postback) field of the `messaging_postback` webhook.
          type: object
          properties:
            payload:
              description: payload parameter that was defined with the button.
              type: string
        account_linking:
          description: >
            A trimmed down version of the [account_linking](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_account_linking#account_linking) field of the `messaging_account_linking` webhook
          type: object
          properties:
            status:
              type: string
              enum: [linked]
            authorization_code:
              type: string
              description: >
                Value of pass-through authorization_code provided in the
                [Account Linking](https://developers.facebook.com/docs/messenger-platform/account-linking/link-account) flow
  

