---
name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: application.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./application.yaml --key=${{secrets.README_API_KEY}} --id=${{ secrets.README_OAS_APPLICATION_KEY }}
      - name: custom-field.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./custom-field.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_CUSTOM_FIELD_DEFINITION_ID }}
      - name: exports.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./exports.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_EXPORTS_ID }}
      - name: inmessage.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./inmessage.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_INMESSAGE_ID }}
      - name: scenarios.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./scenarios.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_SCENARIOS_DEFINITION_ID }}
      - name: subbot.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./subbot.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_SUBBOT_ID }}
      - name: subbot-api.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./subbot-api.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_SUBBOT_API_ID }}
      - name: synchronize.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./synchronize.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_SYNCHRONIZE_ID }}
      - name: user.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./user.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_USER_ID }}
      - name: embed.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./embed.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_EMBED_ID }}
      - name: ai.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./ai.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_AI_ID }}
      - name: ai-api.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./ai-api.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_AI_API_ID }}
      - name: kakaotalk-send.yaml
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./kakaotalk-send.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_KAKAOTALK_SEND_ID }}
